### ISSUE TITLE
Reload starts on startup of ubuntu

### ISSUE THREAD

**Issue by ubershmekel** [jprichardson/reload#94] opened 2017-05-17 18:19 UTC
I'm not sure if this is a bug here, in supervisor or on my system. But every reboot there is an invocation of 

`node /usr/local/lib/node_modules/reload/lib/reload-server.js 8080 / false localhost /tmp/reload-579540941
5980401 index.html false`

Was my machine hacked or did `npm install -g reload` cause this to be run on startup?

**Comment by kethinov** [comment] 2017-05-17 18:20
Because of https://github.com/jprichardson/reload/issues/13

**Comment by alallier** [comment] 2017-05-17 18:26
Closing duplicate of #13. This will be fixed in Version 2.0.0 which should hopefully be coming out soon. Thanks for the file.

**Closed by alallier** 2017-05-17 18:26 UTC
