### ISSUE TITLE
command line tool and relative script path 'failed loading resource'

### ISSUE THREAD

**Issue by tylerlaberge** [jprichardson/reload#87] opened 2017-04-29 02:05 UTC
My index.html is located within the top-level directory 'src' and has the following script path

    <script src="../production/app.bundle.js"></script>

If I run the reload command from within the top-level directory

    reload --browser --dir src

I get the following error in the browser.

    Failed to load resource: the server responded with a status of 404 (Not Found)  app.bundle.js 

But if I don't use reload and just open index.html like normal it loads the resource just fine.

Also, if I move my index.html into the top-level directory, the same directory as the 'production' folder, such that I have the following script path

        <script src="production/app.bundle.js"></script>

And I run

    reload --browser

It works just fine.

So it seems that I have to have my index.html at the top level directory. Is there a way for me to get this to work so that I don't have to move my index.html file outside of the 'src' folder?

**Comment by yamboy1** [comment] 2017-04-29 02:08
which version are you running

**Comment by yamboy1** [comment] 2017-04-29 02:08
and which node version

**Comment by yamboy1** [comment] 2017-04-29 02:10
Also, what is your directory structure. Just so that I can try to reproduce it

**Comment by tylerlaberge** [comment] 2017-04-29 02:17
reload version: 1.1.3
node version: v6.10.2

directory structure:

- MyProject
  - node_modules
  - production
    - components
      - ...
    - modules
      - ...
    - app.js
    - app.bundle.js
  - src
    - components
      - ...
    - modules
      - ...
    - app.ts
    - index.html
  - package.json
  - tsconfig.json
  - webpack.config.js

**Comment by tylerlaberge** [comment] 2017-04-29 02:19
Also, I'm not sure if this is related, even though I can get it to work by moving the index.html into the top-level directory, within a few minutes reload continually says 'restarting...' and never finishes, and I have to stop the process and start the command again.

**Comment by yamboy1** [comment] 2017-04-29 02:31
Which directory are you running the reload command from

**Comment by tylerlaberge** [comment] 2017-04-29 02:32
directly inside the 'MyProject' directory.

**Comment by yamboy1** [comment] 2017-04-29 02:47
After reproducing what you gave me I figured out what you did wrong. You set the http://localhost to src/index.html. When you tried to access ../production/app.bundle.js, it couldn't find it because it was trying to look further back than the root directory. Which is impossible, because the root directory is the bottom most directory. You will have to move the index.html into the top level directory or move the production folder inside the src folder.

**Comment by yamboy1** [comment] 2017-04-29 02:49
The browser will find the js file if you open index.html via file:///home/username/MyProject/src/index.html, or the equivalent in windows or mac.

**Comment by tylerlaberge** [comment] 2017-04-29 02:54
I see, that makes sense. Well I appreciate the help, thank you!

**Comment by yamboy1** [comment] 2017-04-29 02:55
Although, you could also create a link from src/index.html to localhost/index.html. That will probably do what you want

**Comment by tylerlaberge** [comment] 2017-04-29 03:05
hmm I was thinking of doing something like that but I think I'll just put the index.html in the top-level directory, it's not so bad and it kind of makes sense for it to be there anyway

**Comment by yamboy1** [comment] 2017-04-29 03:06
Yeah, it does

**Comment by yamboy1** [comment] 2017-04-29 03:20
You should probably close this issue

**Closed** 2017-04-29 03:22 UTC
